name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: npm install
      - run: npm run bundle
      - run: npm run bundle:min
      - run: npm run doc
      - run: npm run coverage
      
      - uses: jaywcjlove/coverage-badges-cli@main
      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: coverage/CONTRIBUTORS.svg
          avatarSize: 42

      - run: cp -rp coverage website/build
      # - run: npm install @jsdevtools/npm-publish -g
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-alpha/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-block/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-convert/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-compact/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-colorful/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-circle/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-github/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-chrome/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-hsla/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-rgba/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-hue/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-name/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-material/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-saturation/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-shade-slider/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-sketch/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-slider/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-swatch/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-wheel/package.json
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/drag-event-interactive/package.json

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./packages/color/package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|Â∞èÂºüË∞ÉË∞É‚Ñ¢|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-color@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-color)](https://bundlephobia.com/result?p=@uiw/react-color@${{steps.create_tag.outputs.versionNumber}})
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/react-color/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ```bash
            npm i @uiw/react-color@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.changelog }}

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

    
      - name: üì¶ @uiw/react-color publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-alpha publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-block publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-block
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-convert publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-convert
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-compact publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-compact
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-colorful publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-colorful
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-circle publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-circle
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-github publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-chrome publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-chrome
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-editable-input publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-editable-input
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-editable-input-hsla publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-editable-input-hsla
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-editable-input-rgba publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-editable-input-rgba
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-hue publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-hue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-name publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-name
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-material publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-material
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-saturation publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-saturation
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-shade-slider publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-shade-slider
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-sketch publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-sketch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-slider publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-slider
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-swatch publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-swatch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-color-wheel publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/color-wheel
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: üì¶ @uiw/react-drag-event-interactive publish to NPM
        run: npm publish
        continue-on-error: true
        working-directory: ./packages/drag-event-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}