name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: npm install
    - run: npm run build
    - run: npm install
    - run: npm run bundle
    - run: npm run bundle:min
    - run: npm run doc
    - run: npm run coverage
    
    - uses: jaywcjlove/coverage-badges-cli@main
    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: coverage/CONTRIBUTORS.svg
        avatarSize: 42

    - run: cp -rp coverage website/build
    # - run: npm install @jsdevtools/npm-publish -g
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-alpha/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-block/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-convert/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-compact/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-colorful/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-circle/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-github/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-chrome/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-hsla/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-rgba/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-hue/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-name/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-material/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-saturation/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-shade-slider/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-sketch/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-slider/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-swatch/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-wheel/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/drag-event-interactive/package.json

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./packages/color/package.json

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.3

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.3
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|å°å¼Ÿè°ƒè°ƒâ„¢|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-color@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-color)](https://bundlephobia.com/result?p=@uiw/react-color@${{steps.create_tag.outputs.versionNumber}})
          
          Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/react-color/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

          ```bash
          npm i @uiw/react-color@${{steps.create_tag.outputs.versionNumber}}
          ```

          ${{ steps.changelog.outputs.changelog }}

    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

        
    - name: ğŸ“¦ @uiw/react-color publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color/package.json
    
    - name: ğŸ“¦ @uiw/react-color-alpha publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-alpha/package.json
    
    - name: ğŸ“¦ @uiw/react-color-block publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-block/package.json
    
    - name: ğŸ“¦ @uiw/react-color-convert publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-convert/package.json
    
    - name: ğŸ“¦ @uiw/react-color-compact publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-compact/package.json
    
    - name: ğŸ“¦ @uiw/react-color-colorful publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-colorful/package.json
    
    - name: ğŸ“¦ @uiw/react-color-circle publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-circle/package.json
    
    - name: ğŸ“¦ @uiw/react-color-github publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-github/package.json
    
    - name: ğŸ“¦ @uiw/react-color-chrome publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-chrome/package.json
    
    - name: ğŸ“¦ @uiw/react-color-editable-input publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-editable-input/package.json
    
    - name: ğŸ“¦ @uiw/react-color-editable-input-hsla publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-editable-input-hsla/package.json
    
    - name: ğŸ“¦ @uiw/react-color-editable-input-rgba publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-editable-input-rgba/package.json
    
    - name: ğŸ“¦ @uiw/react-color-hue publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-hue/package.json
    
    - name: ğŸ“¦ @uiw/react-color-name publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-name/package.json
    
    - name: ğŸ“¦ @uiw/react-color-material publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-material/package.json
    
    - name: ğŸ“¦ @uiw/react-color-saturation publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-saturation/package.json
    
    - name: ğŸ“¦ @uiw/react-color-shade-slider publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-shade-slider/package.json
    
    - name: ğŸ“¦ @uiw/react-color-sketch publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-sketch/package.json
    
    - name: ğŸ“¦ @uiw/react-color-slider publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-slider/package.json
    
    - name: ğŸ“¦ @uiw/react-color-swatch publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-swatch/package.json
    
    - name: ğŸ“¦ @uiw/react-color-wheel publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/color-wheel/package.json
    
    - name: ğŸ“¦ @uiw/react-drag-event-interactive publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/drag-event-interactive/package.json